services:
  petitebites-web:
    build: .
    image: petitebites-website:1.0
    container_name: petitebites-container
    ports:
      - "8080:80"   # akses lewat http://localhost:8080
    restart: unless-stopped